# Registration Details for Atlassian
spring.security.oauth2.client.registration.atlassian.client-id=${ATLASSIAN_CLIENT_ID}
spring.security.oauth2.client.registration.atlassian.client-secret=${ATLASSIAN_CLIENT_SECRET}
spring.security.oauth2.client.registration.atlassian.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.atlassian.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.atlassian.scope[0]=read:me
spring.security.oauth2.client.registration.atlassian.scope[1]=read:account
spring.security.oauth2.client.registration.atlassian.scope[2]=read:jira-work
spring.security.oauth2.client.registration.atlassian.scope[3]=manage:jira-project
spring.security.oauth2.client.registration.atlassian.scope[4]=manage:jira-configuration
spring.security.oauth2.client.registration.atlassian.scope[5]=read:jira-user
spring.security.oauth2.client.registration.atlassian.scope[6]=write:jira-work
spring.security.oauth2.client.registration.atlassian.scope[7]=manage:jira-webhook

# Provider Details for Atlassian
spring.security.oauth2.client.provider.atlassian.authorization-uri=https://auth.atlassian.com/authorize?audience=api.atlassian.com&prompt=consent
spring.security.oauth2.client.provider.atlassian.token-uri=https://auth.atlassian.com/oauth/token
spring.security.oauth2.client.provider.atlassian.user-info-uri=https://api.atlassian.com/me
spring.security.oauth2.client.provider.atlassian.user-name-attribute=account_id
