
# Registration Details for Slack
spring.security.oauth2.client.registration.slack.client-id=${SLACK_CLIENT_ID}
spring.security.oauth2.client.registration.slack.client-secret=${SLACK_CLIENT_SECRET}
spring.security.oauth2.client.registration.slack.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.slack.redirect-uri={baseUrl}/login/oauth2/code/slack
spring.security.oauth2.client.registration.slack.scope[0]=openid
spring.security.oauth2.client.registration.slack.scope[1]=email
spring.security.oauth2.client.registration.slack.scope[2]=profile

# Provider Details for Slack
spring.security.oauth2.client.provider.slack.authorization-uri=https://slack.com/openid/connect/authorize
spring.security.oauth2.client.provider.slack.token-uri=https://slack.com/api/openid.connect.token
spring.security.oauth2.client.provider.slack.user-info-uri=https://slack.com/api/openid.connect.userInfo
spring.security.oauth2.client.provider.slack.jwk-set-uri=https://slack.com/openid/connect/keys
spring.security.oauth2.client.provider.slack.user-name-attribute=sub
